services:
  backend:
    image: node
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "80:3000"
    env_file:
      - ./backend/.env
    restart: "always"
    command: npm run start:dev
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: itmanagergame
      MYSQL_USER: itmanagergame_user
      MYSQL_PASSWORD: 123
      MYSQL_PORT: 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", '-uitmanagergame_user', '-p123']
      timeout: 5s
      retries: 10